trigger:
  - development

variables:
  - name: PROJECT_VERSION
    value: "1.0.0"

pool:
  vmImage: "ubuntu-latest"

pr: none

stages:
  - stage: Build_and_Deploy
    displayName: Build_and_Deploy
    jobs:
      - job: Build_and_Deploy
        displayName: Build_and_Deploy
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "20.19.0"
            displayName: "Install Node.js"

          - script: |
              npm install
              npm run build
            displayName: "Build App"

          - task: AzureStaticWebApp@0
            inputs:
              app_location: "/dist"
              skip_app_build: true
              skip_api_build: true
              azure_static_web_apps_api_token: "$(STATIC_WEB_APP_TOKEN)"
            env:
              VITE_BACKEND_URL: $(VITE_BACKEND_URL)
